export const base: string;
export const title: string;
export const year: string;
export const details: string;
export const imageWrapper: string;
export const backdrop1: string;
export const backdrop2: string;
export const backdrop3: string;
export const backdrop4: string;
